#!/bin/bash
set -Ceuo pipefail

DOT_DIRECTORY="${HOME}/dotfiles"
REMOTE_URL="https://github.com/yaito6502/dotfiles.git"

function download() {
	if [ ! -d ${DOT_DIRECTORY} ]; then
		echo "Downloading dotfiles..."
		mkdir ${DOT_DIRECTORY}

		git clone --recursive "${REMOTE_URL}" "${DOT_DIRECTORY}"
		echo $(tput setaf 2)Download dotfiles complete!. ✔︎$(tput sgr0)
	fi
}

download
cd ${DOT_DIRECTORY}
make deploy
make init
