[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
let g:highlightedyank_highlight_duration = 150
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'zefei/vim-wintabs'

[[plugins]]
repo = 'zefei/vim-wintabs-powerline'
hook_add = '''
let g:wintabs_autoclose_vim = 1
map <C-n> <Plug>(wintabs_previous) # 前のバッファへ
map <C-p> <Plug>(wintabs_next) # 次のバッファへ
map <C-q> <Plug>(wintabs_close) # 閉じる
map <C-T>u <Plug>(wintabs_undo) # 元に戻す
map <C-T><C-o> <Plug>(wintabs_only) # 現在のバッファ以外閉じる
map <leader>> <cmd>WintabsMove 1<cr> # タブラインの表示位置を右へ移動
map <leader><lt> <cmd>WintabsMove -1<cr> # タブラインの表示位置を左へ移動
map <C-w><C-l> <Plug>(wintabs_move_to_window_right) # 右のウィンドウのタブラインへ移動
map <C-w><C-h> <Plug>(wintabs_move_to_window_left) # 左のウィンドウのタブラインへ移動
map <C-w><C-k> <Plug>(wintabs_move_to_window_above) # 上のウィンドウのタブラインへ移動
map <C-w><C-j> <Plug>(wintabs_move_to_window_below) # 下のウィンドウのタブラインへ移動
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
